apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: ghost
    image: docker.io/ghost
    securityContext:
      readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: ghost
    image: docker.io/ghost
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod03
spec:
  containers:
  - name: ghost
    image: docker.io/ghost
  - name: busybox
    image: docker.io/busybox
    securityContext:
      readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Pod
metadata:
  name: goodpod01
spec:
  containers:
  - name: ghost
    image: docker.io/ghost
    securityContext:
      readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Pod
metadata:
  name: goodpod02
spec:
  containers:
  - name: ghost
    image: docker.io/ghost
    securityContext:
      readOnlyRootFilesystem: true
  - name: nginx
    image: docker.io/nginx
    securityContext:
      readOnlyRootFilesystem: true
